version: '3.9'

services:
  backend:
    build: ./backend
    container_name: nodejs_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
